--Q2
SELECT DISTINCT JOB
FROM EMP;

--Q3 부서 번호 내림차순, 부서 번호 같음, 사원 이름 오름차순
SELECT
    EMPNO AS EMPLOYEE_NO,
    ENAME AS EMPLOYEE_NAME,
    MGR AS MANAGER,
    SAL AS SALARY,
    COMM AS COMMISSION,
    DEPTNO AS DEPARTMENT_NO
    FROM EMP
ORDER BY DEPTNO DESC,ENAME;

--5장
--Q1
SELECT *
    FROM EMP
WHERE ENAME LIKE '%S';

--Q2
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND JOB = 'SALESMAN';

--Q3
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE DEPTNO IN(20,30)
AND SAL > 2000;

--Q3-1
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = (20)
AND SAL > 2000
UNION
SELECT EMPNO,ENAME,JOB,SAL,DEPTNO
FROM EMP
WHERE DEPTNO = (30)
AND SAL > 2000;

--Q4
SELECT EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
FROM EMP
WHERE SAL < 2000
OR SAL > 3000;

--Q5
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE DEPTNO = 30
AND ENAME LIKE '%E%'
AND SAL NOT BETWEEN 1000 AND 2000;

--Q6
SELECT EMPNO,ENAME,JOB, MGR, HIREDATE, SAL ,COMM, DEPTNO
FROM EMP
WHERE COMM IS NULL
AND MGR IS NOT NULL
AND JOB IN('MANAGER','CLERK')
AND ENAME NOT LIKE '_L%';


